# Generated by Django 4.1.4 on 2022-12-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcard',
            name='Archetype',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='Elemental',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='Hebrew_Alphabet',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='Mythical_Spiritual',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='Numerology',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='Questions_to_Ask',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='tarotcard',
            name='meanings',
        ),
    ]
