# Generated by Django 4.1.4 on 2022-12-10 21:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0003_tarotcard_keywords_tarotcard_meanings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='meanings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='questions_to_ask',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
