# Generated by Django 4.1.4 on 2022-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0005_alter_siteuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='note',
            name='interpretation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
