# Generated by Django 4.1.4 on 2022-12-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0006_rename_content_note_description_note_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinspread',
            name='orientation',
            field=models.BooleanField(),
        ),
    ]
