# Generated by Django 4.1.4 on 2022-12-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0007_alter_cardinspread_orientation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinspread',
            old_name='orientation',
            new_name='reverse',
        ),
    ]
