# Generated by Django 4.1.4 on 2023-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0010_siteuser_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='cellPhoneNumber',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
