# Generated by Django 4.1.4 on 2023-01-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0011_siteuser_cellphonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='cellPhoneNumber',
            new_name='cell_phone_number',
        ),
        migrations.RenameField(
            model_name='siteuser',
            old_name='phoneCode',
            new_name='phone_code',
        ),
    ]
