# Generated by Django 4.1.4 on 2023-01-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0012_rename_cellphonenumber_siteuser_cell_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='cell_phone_number',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='phone_code',
        ),
    ]
