# Generated by Django 4.1.4 on 2023-01-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0013_remove_siteuser_cell_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='cell_phone_number',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
