# Generated by Django 4.1.4 on 2023-01-10 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_app', '0014_siteuser_cell_phone_number_siteuser_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamEntry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('associations', models.TextField()),
                ('inner_dynamics', models.TextField()),
                ('interpretation', models.TextField()),
                ('ritual', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
